title = "AitherZero GitLeaks Configuration"
description = "GitLeaks configuration for AitherZero PowerShell automation framework"

# Global allowlist for false positives
[allowlist]
description = "Allowlist for legitimate test data and non-sensitive patterns"

# Paths to exclude from scanning
paths = [
  "tests/**/*",
  "**/*.Tests.ps1",
  "**/*.Enhanced.Tests.ps1",
  "backups/**/*",
  "docs/**/*",
  "examples/**/*",
  "samples/**/*"
]

# Specific patterns to allow
regexes = [
  # Test encryption keys (clearly marked as test data)
  "test-encryption-key",
  "test-api-key",
  "TestModule.*api",
  "mock.*key",
  "example.*key",
  "sample.*key",
  "demo.*key",
  # PowerShell secure string generation (legitimate security practice)
  "ConvertTo-SecureString.*ToBase64String",
  # Test database connections
  "Server=localhost.*test",
  "Database=.*test",
  # Configuration test values
  "ConfigurationCore.*test",
  "ConfigurationBackupRestore.*test"
]

# Commits to ignore (if needed)
commits = []

# Override specific rules for PowerShell context
[[rules]]
description = "Generic API Key"
id = "generic-api-key"
regex = '''(?i)(?:key|api[_-]?key|token|secret|password)\s*[:=]\s*['\"]?[a-zA-Z0-9+/]{16,}['\"]?'''
path = '''.*\.(ps1|psm1|psd1)$'''
# Exclude test files and legitimate PowerShell patterns
allowlist.paths = [
  "tests/**/*",
  "**/*.Tests.ps1",
  "**/*.Enhanced.Tests.ps1",
  "backups/**/*"
]
allowlist.regexes = [
  "test-.*-key",
  "ConvertTo-SecureString.*ToBase64String",
  "# Test|# Mock|# Example|# Sample",
  "TestModule|ConfigurationCore|ConfigurationBackupRestore"
]

[[rules]]
description = "Base64 Encoded Data"
id = "base64-encoded"
regex = '''(?i)(?:secret|key|token|password)\s*[:=]\s*['\"]?[A-Za-z0-9+/]{40,}={0,2}['\"]?'''
path = '''.*\.(ps1|psm1|psd1)$'''
allowlist.paths = [
  "tests/**/*",
  "**/*.Tests.ps1",
  "**/*.Enhanced.Tests.ps1",
  "backups/**/*"
]
allowlist.regexes = [
  "ConvertTo-SecureString.*ToBase64String",
  "# Test|# Mock|# Example"
]

# PowerShell specific rules (more permissive for legitimate use)
[[rules]]
description = "PowerShell Secure String"
id = "powershell-secure-string"
regex = '''ConvertTo-SecureString\s+.*-AsPlainText'''
path = '''.*\.(ps1|psm1|psd1)$'''
# Allow legitimate secure string usage
allowlist.regexes = [
  "ConvertTo-SecureString.*ToBase64String.*Force",
  "Generate.*key",
  "New.*key",
  "Create.*key"
]

# Exclude certain file types and paths entirely
[allowlist]
files = [
  # Documentation and examples
  "README.md",
  "docs/**/*",
  "examples/**/*",
  "samples/**/*",
  # Test files
  "tests/**/*",
  "**/*.Tests.ps1",
  "**/*.Enhanced.Tests.ps1",
  # Backup files
  "backups/**/*",
  # Configuration templates
  "templates/**/*",
  # Build artifacts
  "build/**/*",
  "dist/**/*",
  ".vscode/**/*",
  ".github/**/*"
]

# Specific stop words that indicate legitimate usage
stopwords = [
  "test",
  "example",
  "sample",
  "demo",
  "mock",
  "template",
  "placeholder",
  "dummy",
  "fake",
  "development",
  "staging",
  "localhost",
  "127.0.0.1"
]