# GitGuardian configuration for AitherZero
version: 2

# Paths to ignore during secret scanning
paths-ignore:
  # Test data and fixtures
  - tests/helpers/TEST_PASSWORDS.md
  - tests/data/**
  - tests/Fixtures/**
  - tests/archive/**
  - tests/Critical/**
  
  # Module test directories
  - aither-core/modules/SecureCredentials/tests/**
  - aither-core/modules/*/tests/**
  - "**/*.Tests.ps1"
  
  # Example and demo scripts
  - examples/**
  - demo/**
  - scripts/examples/**
  
  # Build artifacts
  - build/**
  - dist/**
  - TestResults/**
  - tests/results/**
  
  # Documentation
  - docs/**
  - "*.md"
  
  # Configuration templates
  - configs/templates/**
  - opentofu/templates/**

# Specific detectors to ignore
detectors-ignore:
  # Common false positives in infrastructure code
  - generic_high_entropy_secret  # Often triggers on hashes and IDs
  - base64_encoded_secret        # Common in example configs
  
# Custom patterns to ignore (regexes)
ignored-matches:
  # Example/test credentials
  - 'password\s*=\s*["\']?(test|example|demo|password|changeme|admin|secret)["\']?'
  - 'ComputerName\s*=\s*["\']?\w+["\']?'  # PowerShell ComputerName parameters
  - 'Name\s*=\s*["\']?(DC|LAB|TEST|DEMO|EXAMPLE)-\w+["\']?'  # Test computer names
  
  # Dynamic test data patterns
  - 'Test-\d{4}!Pwd'  # Dynamic test passwords
  - 'test-key-\d{6}'  # Dynamic test API keys
  - 'valid-key'       # Common test API key placeholder
  - '\$script:Test(Password|APIKey|Username)'  # Test variable declarations
  - 'PesterTest-.*'   # Pester test identifiers
  - 'Get-Random.*Pwd' # Dynamic password generation patterns
  
  # Test certificates and keys
  - 'BEGIN (TEST|EXAMPLE|DEMO) CERTIFICATE'
  - 'test_?cert|demo_?cert|example_?cert'
  
  # Infrastructure placeholders
  - 'terraform\.tfvars\.example'
  - 'variable\s+".*_password"\s*{\s*default\s*='
  - 'resource_group_name\s*=\s*".*-test-.*"'

# Known test files that may contain example secrets
allowed-patterns:
  - filepath: tests/helpers/TEST_PASSWORDS.md
    reason: Documentation of test credentials for development
    
  - filepath: tests/data/TestCA.cer
    reason: Test certificate for development
    
  - filepath: configs/example-*.json
    reason: Example configuration files with placeholder values
    
  - filepath: aither-core/modules/SecureCredentials/tests/SecureCredentials.Security.Tests.ps1
    reason: Security module test file with dynamically generated test data for testing encryption functionality
    
  - filepath: tests/Critical/API-NonInteractive-Modes.Tests.ps1
    reason: API testing with placeholder authentication keys for testing purposes
    
  - filepath: "**/*.Tests.ps1"
    reason: Pester test files with dynamically generated test data