# TruffleHog v3.89+ configuration for AitherZero
# This file configures TruffleHog to reduce false positives in our PowerShell automation framework

# File path exclusions (TruffleHog v3.89+ format)
allowlist:
  paths:
    - "tests/**/*"
    - "**/*.Tests.ps1" 
    - "**/*.Enhanced.Tests.ps1"
    - "backups/**/*"
    - "docs/**/*"
    - "examples/**/*"
    - "samples/**/*"
    - "templates/**/*"
    - ".vscode/**/*"
    - ".github/**/*"
    - "build/**/*"
    - "dist/**/*"
    
  # Allowlist patterns for legitimate test/example values
  regexes:
    # Test and example patterns
    - "test-.*-key"
    - "mock-.*-key"  
    - "example-.*-key"
    - "sample-.*-key"
    - "demo-.*-key"
    
    # PowerShell legitimate patterns
    - "ConvertTo-SecureString.*ToBase64String"
    - "Generate.*key"
    - "New.*key"
    - "Create.*key"
    
    # Test database and API patterns
    - "localhost.*test"
    - "127\\.0\\.0\\.1.*test"
    - "Database=.*test"
    - "Server=localhost"
    
    # Configuration test patterns
    - "ConfigurationCore.*test"
    - "ConfigurationBackupRestore.*test"
    - "TestModule.*api"