# Example lab configuration for OpenTofuProvider module
# This file demonstrates a complete lab infrastructure setup

hyperv:
  host: "hyperv-01.lab.local"
  user: "lab\\administrator"
  # Note: In production, use Set-SecureCredentials instead of plain text
  password: "SecurePassword123!"
  port: 5986
  https: true
  insecure: false
  use_ntlm: true
  tls_server_name: "hyperv-01.lab.local"
  # Certificate paths - generate using Prepare-HyperVProvider.ps1
  cacert_path: "./certs/ca.pem"
  cert_path: "./certs/client-cert.pem"
  key_path: "./certs/client-key.pem"
  # VM storage location
  vm_path: "C:\\VMs"
  # Script execution path for WinRM
  script_path: "C:/Temp/tofu_%RAND%.cmd"
  # Connection timeout
  timeout: "30s"

# Virtual switch configuration
switch:
  name: "Lab-Internal-Switch"
  net_adapter_names:
    - "Ethernet"
    - "Wi-Fi"

# Virtual machine configurations
vms:
  # Development VMs
  - name_prefix: "dev-vm"
    count: 2
    vhd_size_bytes: 21474836480  # 20GB
    iso_path: "C:\\ISOs\\ubuntu-20.04.iso"
    memory_startup_bytes: 2147483648  # 2GB
    processor_count: 2
    network_adaptors:
      - name: "Network Adapter"
        switch_name: "Lab-Internal-Switch"
    
  # Test VMs  
  - name_prefix: "test-vm"
    count: 1
    vhd_size_bytes: 32212254720  # 30GB
    iso_path: "C:\\ISOs\\windows-server-2022.iso"
    memory_startup_bytes: 4294967296  # 4GB
    processor_count: 4
    network_adaptors:
      - name: "Network Adapter"
        switch_name: "Lab-Internal-Switch"

# Lab metadata
metadata:
  name: "Development Lab Environment"
  version: "1.0.0"
  created_by: "Lab Administrator"
  purpose: "Development and testing environment"
  tags:
    - "development"
    - "testing"
    - "lab"
    - "hyperv"
