name: "ℹ️ PSScriptAnalyzer Information"
description: "PSScriptAnalyzer informational finding for code improvement consideration"
title: "[PSScriptAnalyzer] [INFO] [RULENAME] - SUMMARY"
labels: 
  - "code-quality"
  - "psscriptanalyzer"
  - "information"
  - "priority:low"
  - "enhancement"
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## ℹ️ PSScriptAnalyzer Information
        
        This issue was automatically created by the PSScriptAnalyzer integration system. 
        **Information-level findings are suggestions for code improvement and can be addressed when convenient.**

  - type: input
    id: rule-name
    attributes:
      label: "Rule Name"
      description: "PSScriptAnalyzer rule that provided this information"
      placeholder: "e.g., PSProvideCommentHelp"
    validations:
      required: true

  - type: input
    id: file-path
    attributes:
      label: "File Path"
      description: "Relative path to the file"
      placeholder: "e.g., aither-core/modules/ModuleName/Private/Helper.ps1"
    validations:
      required: true

  - type: input
    id: line-number
    attributes:
      label: "Line Number"
      description: "Line number where the suggestion applies"
      placeholder: "e.g., 42"
    validations:
      required: true

  - type: textarea
    id: message
    attributes:
      label: "Information Message"
      description: "PSScriptAnalyzer informational message"
      placeholder: "Paste the informational message from PSScriptAnalyzer"
    validations:
      required: true

  - type: dropdown
    id: improvement-type
    attributes:
      label: "Improvement Type"
      description: "What type of improvement does this suggest?"
      options:
        - "Documentation enhancement"
        - "Code style improvement"
        - "Performance optimization opportunity"
        - "Maintainability improvement"
        - "Best practice suggestion"
        - "Cross-platform compatibility"
        - "Other"
      default: 0

  - type: dropdown
    id: effort-level
    attributes:
      label: "Effort Level"
      description: "How much effort would this improvement require?"
      options:
        - "Minimal - Quick fix"
        - "Low - Simple change"
        - "Medium - Some refactoring"
        - "High - Significant work"
        - "Unknown - Needs investigation"
      default: 0

  - type: checkboxes
    id: improvement-benefits
    attributes:
      label: "Potential Benefits"
      description: "What benefits would addressing this provide?"
      options:
        - label: "Improved code readability"
          required: false
        - label: "Better maintainability"
          required: false
        - label: "Enhanced documentation"
          required: false
        - label: "Performance improvement"
          required: false
        - label: "Better error handling"
          required: false
        - label: "Increased test coverage"
          required: false
        - label: "Framework consistency"
          required: false

  - type: textarea
    id: current-code
    attributes:
      label: "Current Code"
      description: "The current code that could be improved"
      render: powershell
      placeholder: |
        # Current implementation
        function Example-Function {
            # Current code here
        }
    validations:
      required: false

  - type: textarea
    id: suggested-improvement
    attributes:
      label: "Suggested Improvement"
      description: "How this could be improved"
      render: powershell
      placeholder: |
        # Improved implementation
        function Example-Function {
            <#
            .SYNOPSIS
                Brief description of what this function does
            #>
            # Improved code here
        }
    validations:
      required: false

  - type: dropdown
    id: address-when
    attributes:
      label: "When to Address"
      description: "When should this improvement be considered?"
      options:
        - "Next maintenance cycle"
        - "When refactoring this module"
        - "During major version update"
        - "When time permits"
        - "Consider for automation"
        - "May not be worth addressing"
      default: 0

  - type: input
    id: bugz-id
    attributes:
      label: "Bug Tracking ID"
      description: "Associated .bugz file tracking ID (if available)"
      placeholder: "e.g., PSSA-9012"
    validations:
      required: false

  - type: checkboxes
    id: automation-candidate
    attributes:
      label: "Automation Considerations"
      description: "Could this be addressed through automation?"
      options:
        - label: "Good candidate for automated fixing"
          required: false
        - label: "Could be partially automated"
          required: false
        - label: "Add to automated documentation generation"
          required: false
        - label: "Include in bulk improvement scripts"
          required: false

  - type: textarea
    id: analysis-context
    attributes:
      label: "Analysis Context"
      description: "Context from the PSScriptAnalyzer analysis"
      render: json
      placeholder: |
        {
          "analysisDate": "2025-07-06T10:30:00Z",
          "moduleContext": "ModuleName",
          "qualityScore": 90,
          "totalInformationalFindings": 15,
          "configuration": "UtilityModule",
          "relatedFindings": 2
        }
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ---
        
        ## 💡 Improvement Guidelines
        
        **For Information-level findings:**
        1. **Optional Improvements** - These are suggestions, not requirements
        2. **Batch Processing** - Group similar improvements together
        3. **Timing Flexibility** - Address when convenient or during refactoring
        4. **Automation Opportunities** - Many can be automated
        
        **Decision Framework:**
        - **High Value, Low Effort** → Address soon
        - **High Value, High Effort** → Plan for future iteration
        - **Low Value, Low Effort** → Consider for automation
        - **Low Value, High Effort** → May not be worth addressing
        
        **Automated Processing:**
        - Some informational findings can be automatically addressed
        - This issue may be auto-closed during bulk improvements
        - Status tracked in .bugz files for reporting
        
        **Benefits Tracking:**
        - Code quality score improvements
        - Enhanced maintainability metrics
        - Better development experience
        
        **Related Documentation:**
        - [PSScriptAnalyzer Rules Documentation](https://github.com/PowerShell/PSScriptAnalyzer/blob/master/RuleDocumentation)
        - [Code Improvement Guidelines](docs/code-improvement-guidelines.md)
        - [Automation Opportunities](docs/automation-candidates.md)