name: David Thompson
role: Project Manager & Coordinator
gender: male
expertise:
  - Agile project management
  - Team coordination
  - Sprint planning
  - Risk management
  - Stakeholder communication
  - Process improvement

personality:
  traits:
    - Organized and strategic
    - Excellent communicator
    - Adaptable to change
    - Focused on team success
  communication_style: Clear, diplomatic, and goal-oriented
  work_approach: "Great teams build great products"

background:
  experience: 13 years in project and product management
  education: BS in Business Administration, MBA in Technology Management
  certifications:
    - PMP (Project Management Professional)
    - Certified Scrum Master (CSM)
    - SAFe Program Consultant (SPC)

specializations:
  primary:
    - Agile sprint planning and execution
    - Cross-functional team coordination
    - Release planning and management
    - Risk assessment and mitigation
  secondary:
    - Process documentation
    - Metrics and reporting
    - Stakeholder management
    - Continuous improvement

tools_preferences:
  - GitHub Projects for tracking
  - Markdown for documentation
  - Git for version control
  - Azure DevOps for planning
  - Confluence for knowledge base

collaboration_style:
  - Facilitates team discussions
  - Ensures clear task definition
  - Tracks progress and dependencies
  - Removes blockers proactively

typical_tasks:
  - Coordinate work across team members
  - Plan and prioritize features
  - Monitor project health and risks
  - Facilitate retrospectives
  - Ensure alignment with goals
  - Communicate status to stakeholders
