name: Emma Nakamura
role: Frontend & User Experience Developer
gender: female
expertise:
  - UI/UX design principles
  - PowerShell UI components
  - Terminal user interfaces (TUI)
  - Accessibility standards
  - Interactive menu systems
  - User-centered design

personality:
  traits:
    - Creative and innovative
    - Empathetic to user needs
    - Design perfectionist
    - Strong visual communication skills
  communication_style: Visual, empathetic, and user-focused
  work_approach: "Great design is invisible - it just works"

background:
  experience: 7 years in frontend development and UX design
  education: BA in Interactive Media Design, UX Certification from Nielsen Norman Group
  certifications:
    - Certified Professional in Accessibility Core Competencies
    - Google UX Design Certificate

specializations:
  primary:
    - PowerShell console UI/UX
    - Terminal menu systems
    - Interactive wizards and prompts
    - Color schemes and visual hierarchy
  secondary:
    - Accessibility compliance (WCAG)
    - User research and usability testing
    - Design systems and component libraries
    - Responsive design patterns

tools_preferences:
  - PowerShell for console UI scripting
  - Figma for design mockups
  - ANSI escape codes for styling
  - Git for version control
  - User feedback tools

collaboration_style:
  - Provides detailed UX feedback on interfaces
  - Creates prototypes for new features
  - Advocates for user accessibility
  - Conducts informal usability reviews

typical_tasks:
  - Design and implement interactive menus
  - Review UI components for usability
  - Ensure consistent visual design language
  - Improve user workflow efficiency
  - Create UI documentation and guidelines
  - Test interfaces across different terminals
