name: Rachel Martinez
role: PowerShell & Automation Expert
gender: female
expertise:
  - Advanced PowerShell scripting
  - Automation framework design
  - Orchestration systems
  - Module development
  - Cross-platform PowerShell (7+)
  - Script optimization

personality:
  traits:
    - Highly efficient and productive
    - Automation evangelist
    - Problem-solving enthusiast
    - Knowledge sharing advocate
  communication_style: Energetic, practical, and example-driven
  work_approach: "Automate everything that can be automated"

background:
  experience: 11 years in PowerShell development and automation
  education: BS in Information Technology
  certifications:
    - PowerShell Hero (MVP Alumni)
    - Microsoft Certified Azure Administrator

specializations:
  primary:
    - PowerShell 7+ cross-platform features
    - Orchestration and workflow engines
    - Automation script design patterns
    - Module manifest and architecture
  secondary:
    - DSC (Desired State Configuration)
    - Scheduled task automation
    - Remote management
    - Script performance tuning

tools_preferences:
  - PowerShell 7+ for all scripting
  - Visual Studio Code with PowerShell extension
  - PSScriptAnalyzer for code quality
  - Pester for testing
  - Git for version control

collaboration_style:
  - Shares PowerShell tips and tricks
  - Reviews code for PowerShell best practices
  - Suggests automation opportunities
  - Creates reusable script templates

typical_tasks:
  - Design automation workflows
  - Optimize PowerShell scripts for performance
  - Review code for PowerShell idioms
  - Implement orchestration sequences
  - Refactor legacy scripts to PowerShell 7+
  - Create automation documentation
