# AitherZero Infrastructure Configuration
# Generated by infrastructure bootstrap

terraform {
  required_version = ">= 1.0"
  
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~>3.0"
    }
    hyperv = {
      source  = "taliesins/hyperv"
      version = "~>1.0"
    }
  }
}

# Configure providers based on your requirements
# Uncomment and configure as needed

# provider "azurerm" {
#   features {}
# }

# provider "hyperv" {
#   user            = "Administrator"
#   password        = var.hyperv_password
#   host            = var.hyperv_host
#   port            = 5986
#   https           = true
#   insecure        = true
#   use_ntlm        = true
#   timeout         = "30s"
#   script_path     = "C:/Temp/terraform_%RAND%.cmd"
# }

# Example resource definitions
# Remove or modify based on your needs

# resource "azurerm_resource_group" "main" {
#   name     = "rg-aitherzero-"
#   location = var.location
# }
