---
name: Claude Bot Coordinator

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  coordinate:
    runs-on: ubuntu-latest
    steps:
      - name: Detect claude-bot and coordinate with Copilot
        uses: actions/github-script@v7
        with:
          script: |
            const comment = context.payload.comment;
            const issueNumber = context.issue?.number || context.payload.pull_request?.number;

            if (!issueNumber) return;

            // Check if comment is from claude-bot
            if (comment.user.login === 'claude-bot' || comment.user.login.includes('claude')) {
              console.log('claude-bot activity detected');

              // Wait a moment for comment to be visible
              await new Promise(resolve => setTimeout(resolve, 2000));

              // Post coordination comment
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issueNumber,
                body: `🤝 **AI Coordination**\n\n@claude-bot has provided feedback above.\n\n@copilot please review claude-bot's suggestions and implement the recommended changes.\n\n---\n*Automated coordination by AitherZero*`
              });

              console.log('Coordination comment posted');
            }
