---
name: 🧹 Close Auto-Created Issues

# One-time workflow to close all existing auto-created issues
# Run this manually before implementing new intelligent issue creation
on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Dry run - preview what would be closed without actually closing'
        type: boolean
        default: true
      close_reason:
        description: 'Reason for closing issues'
        type: choice
        options:
          - 'not_planned'
          - 'completed'
        default: 'not_planned'

permissions:
  issues: write
  contents: read

jobs:
  cleanup-issues:
    name: 🧹 Close Auto-Created Issues
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v4

      - name: 🔍 Find and Close Auto-Created Issues
        uses: actions/github-script@v7
        with:
          script: |
            const dryRun = '${{ github.event.inputs.dry_run }}' === 'true';
            const closeReason = '${{ github.event.inputs.close_reason }}';
            
            console.log(`🧹 Cleanup Mode: ${dryRun ? 'DRY RUN (preview only)' : 'ACTIVE (will close issues)'}`);
            console.log(`📋 Close Reason: ${closeReason}`);
            console.log('');

            // Find all auto-created issues (checking both label variations)
            const { data: autoCreatedIssues } = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              labels: 'auto-created',
              per_page: 100
            });
            
            const { data: automatedIssues } = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              labels: 'automated-issue',
              per_page: 100
            });
            
            // Combine and deduplicate by issue number
            const issueMap = new Map();
            [...autoCreatedIssues, ...automatedIssues].forEach(issue => {
              issueMap.set(issue.number, issue);
            });
            const issues = Array.from(issueMap.values());

            console.log(`Found ${issues.length} auto-created/automated issues to process`);
            console.log(`  - auto-created label: ${autoCreatedIssues.length}`);
            console.log(`  - automated-issue label: ${automatedIssues.length}`);
            console.log('');

            if (issues.length === 0) {
              console.log('✅ No auto-created issues found. Repository is clean!');
              return;
            }

            // Group issues by type for reporting
            const issuesByType = {};
            for (const issue of issues) {
              const labels = issue.labels.map(l => l.name);
              let type = 'other';
              
              if (labels.includes('psscriptanalyzer')) type = 'code-quality';
              else if (labels.includes('unit-tests')) type = 'testing';
              else if (labels.includes('security')) type = 'security';
              else if (labels.includes('maintenance')) type = 'maintenance';
              
              if (!issuesByType[type]) issuesByType[type] = [];
              issuesByType[type].push(issue);
            }

            // Report what will be closed
            console.log('📊 Issues by Type:');
            for (const [type, typeIssues] of Object.entries(issuesByType)) {
              console.log(`  ${type}: ${typeIssues.length} issues`);
              typeIssues.forEach(issue => {
                console.log(`    - #${issue.number}: ${issue.title}`);
              });
            }
            console.log('');

            if (dryRun) {
              console.log('🔍 DRY RUN MODE: No issues will be closed');
              console.log('');
              console.log('To actually close these issues, run this workflow again with:');
              console.log('  dry_run: false');
              console.log('');
              console.log(`Total issues that would be closed: ${issues.length}`);
              return;
            }

            // Close all auto-created issues
            console.log('🧹 Closing auto-created issues...');
            console.log('');

            const closeMessage = `## 🧹 Automated Cleanup

This auto-created issue is being closed as part of a system-wide cleanup.

**Reason:** Migrating to improved intelligent issue creation system with:
- Better deduplication logic
- PR-based workflow for grouped fixes
- More detailed context (file, domain, branch info)
- Manual priority assignment with recommendations
- Prevention of duplicate issues across branches

If this issue represents a real problem that still exists, it will be recreated by the new system with more context and better grouping.

**Next Steps:**
1. New issues will be created with improved deduplication
2. Similar issues will be grouped in PRs
3. Manual priority assignment required (P1-P10)
4. Copilot will be assigned to PRs, not individual issues

---
**Closed by:** Automated cleanup workflow
**Date:** ${new Date().toISOString()}`;

            let closedCount = 0;
            for (const issue of issues) {
              try {
                // Add closing comment
                await github.rest.issues.createComment({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: issue.number,
                  body: closeMessage
                });

                // Close the issue
                await github.rest.issues.update({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: issue.number,
                  state: 'closed',
                  state_reason: closeReason
                });

                closedCount++;
                console.log(`✅ Closed issue #${issue.number}: ${issue.title}`);
              } catch (error) {
                console.log(`❌ Failed to close issue #${issue.number}: ${error.message}`);
              }
            }

            console.log('');
            console.log(`✅ Cleanup complete! Closed ${closedCount}/${issues.length} issues`);
            
            if (closedCount < issues.length) {
              console.log(`⚠️ Warning: ${issues.length - closedCount} issues failed to close`);
            }

      - name: 📝 Summary
        if: always()
        shell: bash
        run: |
          if [ -n "$GITHUB_STEP_SUMMARY" ]; then
            cat >> $GITHUB_STEP_SUMMARY << 'EOF'
          ## 🧹 Auto-Created Issues Cleanup

          This workflow closes all existing auto-created issues as part of migrating to an improved issue creation system.

          ### Improvements in New System:
          - ✅ Better deduplication by type, file, and domain
          - ✅ PR-based workflow for grouped fixes
          - ✅ More detailed context (branch, file, workflow info)
          - ✅ Manual priority assignment with recommendations
          - ✅ Prevention of duplicate issues across branches
          - ✅ Copilot assigned to PRs instead of individual issues

          ### Status
          Run completed. Check logs above for details on issues processed.
          
          **Mode:** ${{ github.event.inputs.dry_run == 'true' && 'DRY RUN (preview only)' || 'ACTIVE (issues closed)' }}
          EOF
          fi
