---
name: "Code Quality Remediation"

"on":
  schedule:
    # Run weekly on Saturdays at 3 AM UTC
    - cron: '0 3 * * 6'
  workflow_dispatch:
    inputs:
      remediation_type:
        description: 'Type of remediation to perform'
        required: true
        default: 'comprehensive'
        type: choice
        options:
          - comprehensive
          - formatting-only
          - rules-only
          - critical-only
      create_pr:
        description: 'Create pull request with fixes'
        required: false
        default: true
        type: boolean
      dry_run:
        description: 'Show what would be fixed without making changes'
        required: false
        default: false
        type: boolean

permissions:
  contents: write
  pull-requests: write

env:
  POWERSHELL_TELEMETRY_OPTOUT: 1
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_NOLOGO: true

defaults:
  run:
    shell: pwsh

jobs:
  analyze-quality:
    name: "Analyze Code Quality"
    runs-on: ubuntu-latest
    timeout-minutes: 15
    outputs:
      has-issues: ${{ steps.analysis.outputs.has-issues }}
      issue-count: ${{ steps.analysis.outputs.issue-count }}
      critical-count: ${{ steps.analysis.outputs.critical-count }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install PSScriptAnalyzer
        run: |
          Install-Module -Name PSScriptAnalyzer -Force -Scope CurrentUser

      - name: Run comprehensive analysis
        id: analysis
        run: |
          Write-Host "🔍 Running comprehensive PowerShell code analysis..."

          # Get all PowerShell files
          $files = Get-ChildItem -Include "*.ps1", "*.psm1", "*.psd1" -Recurse |
                   Where-Object { $_.FullName -notlike "*\.git*" -and $_.FullName -notlike "*test*" }

          Write-Host "Found $($files.Count) PowerShell files to analyze"

          $allIssues = @()
          $fixableIssues = @()

          foreach ($file in $files) {
            Write-Host "Analyzing: $($file.Name)"

            $issues = Invoke-ScriptAnalyzer -Path $file.FullName -Severity Error,Warning,Information -IncludeDefaultRules

            if ($issues) {
              foreach ($issue in $issues) {
                $issueObj = [PSCustomObject]@{
                  File = $file.FullName.Replace((Get-Location).Path, "").TrimStart('/')
                  Line = $issue.Line
                  Column = $issue.Column
                  Severity = $issue.Severity
                  RuleName = $issue.RuleName
                  Message = $issue.Message
                  ScriptPath = $issue.ScriptPath
                  Fixable = $issue.RuleName -in @(
                    'PSUseConsistentIndentation',
                    'PSUseConsistentWhitespace',
                    'PSAlignAssignmentStatement',
                    'PSUseCorrectCasing',
                    'PSPlaceOpenBrace',
                    'PSPlaceCloseBrace',
                    'PSAvoidTrailingWhitespace',
                    'PSAvoidSemicolonsAsLineTerminators'
                  )
                }
                $allIssues += $issueObj

                if ($issueObj.Fixable) {
                  $fixableIssues += $issueObj
                }
              }
            }
          }

          Write-Host "📊 Analysis Results:"
          Write-Host "  Total issues: $($allIssues.Count)"
          Write-Host "  Fixable issues: $($fixableIssues.Count)"
          Write-Host "  Critical issues: $(($allIssues | Where-Object Severity -eq 'Error').Count)"
          Write-Host "  Warning issues: $(($allIssues | Where-Object Severity -eq 'Warning').Count)"
          Write-Host "  Info issues: $(($allIssues | Where-Object Severity -eq 'Information').Count)"

          # Group by rule for summary
          $ruleGroups = $allIssues | Group-Object RuleName | Sort-Object Count -Descending
          if ($ruleGroups) {
            Write-Host "`n📋 Top issues by rule:"
            foreach ($group in $ruleGroups | Select-Object -First 10) {
              Write-Host "  $($group.Name): $($group.Count) occurrences"
            }
          }

          # Export detailed results
          $allIssues | ConvertTo-Json -Depth 3 | Set-Content "quality-analysis.json"
          $fixableIssues | ConvertTo-Json -Depth 3 | Set-Content "fixable-issues.json"

          # Set outputs
          $hasIssues = if ($allIssues.Count -gt 0) { 'true' } else { 'false' }
          echo "has-issues=$hasIssues" >> $env:GITHUB_OUTPUT
          echo "issue-count=$($allIssues.Count)" >> $env:GITHUB_OUTPUT
          echo "critical-count=$(($allIssues | Where-Object Severity -eq 'Error').Count)" >> $env:GITHUB_OUTPUT

      - name: Upload analysis results
        uses: actions/upload-artifact@v4
        with:
          name: quality-analysis
          path: |
            quality-analysis.json
            fixable-issues.json
          retention-days: 30

  auto-fix:
    name: "Auto-Fix Issues"
    runs-on: ubuntu-latest
    timeout-minutes: 20
    needs: analyze-quality
    if: needs.analyze-quality.outputs.has-issues == 'true' && github.event.inputs.dry_run != 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install tools
        run: |
          Install-Module -Name PSScriptAnalyzer -Force -Scope CurrentUser

      - name: Download analysis results
        uses: actions/download-artifact@v4
        with:
          name: quality-analysis
          path: ./

      - name: Apply automatic fixes
        id: apply-fixes
        run: |
          Write-Host "🔧 Applying automatic fixes..."

          $fixableIssues = Get-Content "fixable-issues.json" | ConvertFrom-Json
          $remediationType = "${{ github.event.inputs.remediation_type }}"

          Write-Host "Remediation type: $remediationType"
          Write-Host "Fixable issues: $($fixableIssues.Count)"

          $fixedFiles = @()
          $appliedFixes = @()

          # Group issues by file for efficient processing
          $fileGroups = $fixableIssues | Group-Object File

          foreach ($fileGroup in $fileGroups) {
            $filePath = $fileGroup.Name
            Write-Host "Processing: $filePath"

            if (-not (Test-Path $filePath)) {
              Write-Host "  ⚠️ File not found: $filePath"
              continue
            }

            $fileIssues = $fileGroup.Group
            $fixesToApply = @()

            # Filter fixes based on remediation type
            switch ($remediationType) {
              'formatting-only' {
                $fixesToApply = $fileIssues | Where-Object {
                  $_.RuleName -in @('PSUseConsistentIndentation', 'PSUseConsistentWhitespace', 'PSAlignAssignmentStatement', 'PSPlaceOpenBrace', 'PSPlaceCloseBrace', 'PSAvoidTrailingWhitespace')
                }
              }
              'rules-only' {
                $fixesToApply = $fileIssues | Where-Object {
                  $_.RuleName -in @('PSUseCorrectCasing', 'PSAvoidSemicolonsAsLineTerminators')
                }
              }
              'critical-only' {
                $fixesToApply = $fileIssues | Where-Object { $_.Severity -eq 'Error' }
              }
              default {
                $fixesToApply = $fileIssues
              }
            }

            if ($fixesToApply.Count -eq 0) {
              Write-Host "  ℹ️ No applicable fixes for this file"
              continue
            }

            try {
              # Use Invoke-Formatter to fix formatting issues
              $formattingRules = $fixesToApply | Where-Object {
                $_.RuleName -in @('PSUseConsistentIndentation', 'PSUseConsistentWhitespace', 'PSPlaceOpenBrace', 'PSPlaceCloseBrace')
              }

              if ($formattingRules.Count -gt 0) {
                Write-Host "  🎨 Applying formatting fixes..."

                $formatterSettings = @{
                  Rules = @{
                    PSUseConsistentIndentation = @{
                      Enable = $true
                      Kind = 'space'
                      IndentationSize = 4
                    }
                    PSUseConsistentWhitespace = @{
                      Enable = $true
                      CheckInnerBrace = $true
                      CheckOpenBrace = $true
                      CheckOpenParen = $true
                      CheckOperator = $true
                      CheckPipe = $true
                      CheckSeparator = $true
                    }
                    PSPlaceOpenBrace = @{
                      Enable = $true
                      OnSameLine = $true
                      NewLineAfter = $true
                      IgnoreOneLineBlock = $true
                    }
                    PSPlaceCloseBrace = @{
                      Enable = $true
                      NewLineAfter = $false
                      IgnoreOneLineBlock = $true
                      NoEmptyLineBefore = $false
                    }
                    PSAlignAssignmentStatement = @{
                      Enable = $true
                      CheckHashtable = $true
                    }
                  }
                }

                $originalContent = Get-Content $filePath -Raw
                $formattedContent = Invoke-Formatter -ScriptDefinition $originalContent -Settings $formatterSettings

                if ($formattedContent -ne $originalContent) {
                  Set-Content -Path $filePath -Value $formattedContent -NoNewline
                  $fixedFiles += $filePath
                  $appliedFixes += "Formatted $($formattingRules.Count) issues in $filePath"
                  Write-Host "  ✅ Applied formatting fixes"
                } else {
                  Write-Host "  ℹ️ No formatting changes needed"
                }
              }

              # Apply other rule-based fixes
              $otherRules = $fixesToApply | Where-Object {
                $_.RuleName -notin @('PSUseConsistentIndentation', 'PSUseConsistentWhitespace', 'PSPlaceOpenBrace', 'PSPlaceCloseBrace', 'PSAlignAssignmentStatement')
              }

              foreach ($rule in $otherRules) {
                switch ($rule.RuleName) {
                  'PSAvoidTrailingWhitespace' {
                    $content = Get-Content $filePath -Raw
                    $newContent = $content -replace '\s+$', ''
                    if ($newContent -ne $content) {
                      Set-Content -Path $filePath -Value $newContent -NoNewline
                      $appliedFixes += "Removed trailing whitespace in $filePath"
                      Write-Host "  ✅ Removed trailing whitespace"
                    }
                  }
                  'PSAvoidSemicolonsAsLineTerminators' {
                    $lines = Get-Content $filePath
                    $modified = $false
                    for ($i = 0; $i -lt $lines.Length; $i++) {
                      if ($lines[$i] -match ';$' -and $lines[$i] -notmatch '["''].*;["'']') {
                        $lines[$i] = $lines[$i] -replace ';$', ''
                        $modified = $true
                      }
                    }
                    if ($modified) {
                      Set-Content -Path $filePath -Value $lines
                      $appliedFixes += "Removed semicolons in $filePath"
                      Write-Host "  ✅ Removed semicolons"
                    }
                  }
                }
              }

            } catch {
              Write-Host "  ❌ Error processing file: $($_.Exception.Message)"
            }
          }

          Write-Host "`n📊 Fix Summary:"
          Write-Host "  Files modified: $($fixedFiles.Count)"
          Write-Host "  Total fixes applied: $($appliedFixes.Count)"

          if ($appliedFixes.Count -gt 0) {
            Write-Host "`n🔧 Applied fixes:"
            foreach ($fix in $appliedFixes) {
              Write-Host "  - $fix"
            }
          }

          # Save fix summary
          @{
            FilesModified = $fixedFiles
            FixesApplied = $appliedFixes
            RemediationType = $remediationType
            Timestamp = (Get-Date -Format "yyyy-MM-ddTHH:mm:ssZ")
          } | ConvertTo-Json -Depth 3 | Set-Content "fix-summary.json"

          $fixesApplied = if ($appliedFixes.Count -gt 0) { 'true' } else { 'false' }
          echo "fixes-applied=$fixesApplied" >> $env:GITHUB_OUTPUT
          echo "files-modified=$($fixedFiles.Count)" >> $env:GITHUB_OUTPUT

      - name: Upload fix results
        uses: actions/upload-artifact@v4
        with:
          name: fix-results
          path: fix-summary.json
          retention-days: 30

      - name: Create pull request
        if: steps.apply-fixes.outputs.fixes-applied == 'true' && github.event.inputs.create_pr == 'true'
        run: |
          # Configure git
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action - Code Quality Bot"

          # Create branch
          $branchName = "code-quality/auto-fix-$(Get-Date -Format 'yyyyMMdd-HHmmss')"
          git checkout -b $branchName

          # Stage changes
          git add .

          # Check if there are changes to commit
          $changes = git diff --staged --name-only
          if (-not $changes) {
            Write-Host "No changes to commit"
            exit 0
          }

          Write-Host "Changes to commit:"
          foreach ($change in $changes) {
            Write-Host "  - $change"
          }

          # Commit changes
          $filesModified = "${{ steps.apply-fixes.outputs.files-modified }}"
          $remedType = "${{ github.event.inputs.remediation_type }}"

          $commitMessage = "Automated code quality fixes ($remedType) - Fixed $filesModified files"

          git commit -m $commitMessage

          # Push branch
          git push origin $branchName

          # Create PR using GitHub CLI
          $prTitle = "🔧 Automated Code Quality Fixes ($remedType)"
          $serverUrl = "${{ github.server_url }}"
          $repository = "${{ github.repository }}"
          $runId = "${{ github.run_id }}"

          $prBody = "## Automated Code Quality Fixes`n`nThis PR contains automatic fixes applied by the Code Quality Remediation workflow.`n`n### Summary`n- Remediation Type: $remedType`n- Files Modified: $filesModified`n- Triggered By: $actor`n- Workflow Run: $serverUrl/$repository/actions/runs/$runId`n`n### Fixes Applied`nThe following types of issues were automatically fixed:`n- Code formatting and indentation`n- Consistent whitespace usage`n- Brace placement`n- Trailing whitespace removal`n- Semicolon cleanup`n`n### Quality Assurance`n- All fixes were applied using PSScriptAnalyzer's built-in formatter`n- No functional changes were made to the code`n- Only formatting and style improvements`n`n### Next Steps`n1. Review the changes in this PR`n2. Run tests to ensure no functionality is broken`n3. Merge when satisfied with the improvements`n`n*This PR was automatically created by the Code Quality Remediation workflow.*"

          gh pr create --title $prTitle --body $prBody --head $branchName --base main

          Write-Host "✅ Pull request created successfully"

  generate-report:
    name: "Generate Quality Report"
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: [analyze-quality, auto-fix]
    if: always() && !cancelled()
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts/

      - name: Generate comprehensive report
        run: |
          Write-Host "📊 Generating code quality report..."

          $timestamp = Get-Date -Format 'yyyy-MM-dd HH:mm:ss UTC'
          $workflow = "${{ github.workflow }}"
          $runId = "${{ github.run_id }}"
          $actor = "${{ github.actor }}"
          $issueCount = "${{ needs.analyze-quality.outputs.issue-count }}"
          $criticalCount = "${{ needs.analyze-quality.outputs.critical-count }}"
          $analysisResult = "${{ needs.analyze-quality.result }}"
          $fixResult = "${{ needs.auto-fix.result }}"
          $remediationType = "${{ github.event.inputs.remediation_type }}"
          $dryRun = "${{ github.event.inputs.dry_run }}"
          $createPR = "${{ github.event.inputs.create_pr }}"

          $criticalStatus = if ($criticalCount -eq '0') { '✅' } else { '❌' }
          $issueStatus = if ([int]$issueCount -lt 50) { '✅' } else { '❌' }

          $report = "# AitherZero Code Quality Report`n`n**Generated**: $timestamp`n**Workflow**: $workflow`n**Run ID**: $runId`n**Triggered By**: $actor`n`n## Quality Metrics`n`n### Analysis Results`n- **Total Issues**: $issueCount`n- **Critical Issues**: $criticalCount`n- **Analysis Status**: $analysisResult`n`n### Remediation Results`n- **Remediation Status**: $fixResult`n- **Remediation Type**: $remediationType`n- **Dry Run**: $dryRun`n- **Create PR**: $createPR`n`n## Quality Targets`n`n| Metric | Current | Target | Status |`n|--------|---------|--------|--------|`n| Critical Issues | $criticalCount | 0 | $criticalStatus |`n| Total Issues | $issueCount | < 50 | $issueStatus |`n`n## Automated Fixes`n`nThe workflow can automatically fix the following types of issues:`n- Code formatting and indentation`n- Consistent whitespace usage`n- Brace placement standardization`n- Trailing whitespace removal`n- Semicolon cleanup`n- Assignment alignment`n`n## Recommendations`n"

          if ([int]$criticalCount -gt 0) {
            $report += "`n### Critical Issues Detected`n"
            $report += "- Review and fix critical issues manually`n"
            $report += "- Critical issues may indicate functional problems`n"
          }

          if ([int]$issueCount -gt 50) {
            $report += "`n### High Issue Count`n"
            $report += "- Consider running remediation more frequently`n"
            $report += "- Review coding standards and practices`n"
          }

          $report += "`n`n### Next Actions`n1. Review any critical issues manually`n2. Run automated remediation if needed`n3. Consider updating coding guidelines`n4. Schedule regular quality checks`n`n---`n*Report generated by AitherZero Code Quality Remediation workflow*"

          $report | Set-Content "quality-report.md"
          Write-Host $report

      - name: Upload quality report
        uses: actions/upload-artifact@v4
        with:
          name: quality-report
          path: quality-report.md
          retention-days: 90

      - name: Quality summary
        run: |
          Write-Host "📊 Code Quality Remediation Summary"
          Write-Host "=================================="
          $analysisResult = "${{ needs.analyze-quality.result }}"
          $fixResult = "${{ needs.auto-fix.result }}"
          $issueCount = "${{ needs.analyze-quality.outputs.issue-count }}"
          $criticalCount = "${{ needs.analyze-quality.outputs.critical-count }}"

          Write-Host "Analysis: $analysisResult"
          Write-Host "Auto-fix: $fixResult"
          Write-Host "Issues found: $issueCount"
          Write-Host "Critical issues: $criticalCount"

          if ($analysisResult -eq "failure") {
            Write-Host "::error::Code quality analysis failed"
            exit 1
          }

          Write-Host "::notice::Code quality remediation completed"
