---
name: Simple AI Coordination

on:
  pull_request:
    types: [opened, synchronize]
  issue_comment:
    types: [created]

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  coordinate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Coordinate
        uses: actions/github-script@v7
        with:
          script: |
            const num = context.issue?.number || context.payload.pull_request?.number;
            if (!num) return;

            const comment = context.payload.comment?.body || '';

            if (comment.includes('@copilot')) {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: num,
                body: '✅ Copilot notified. AitherZero validation will run automatically.'
              });
            }
